/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe: 200 se il processo è up.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bandi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogo globale bandi consolidati (super_admin)
         * @description Lista paginata di bandi consolidati con counter clienti-match.
         *
         *     Risposta: `BandiListPage` (items + total + page + page_size).
         *     Ordering: `created_at DESC`. Idempotente.
         */
        get: operations["list_bandi_bandi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clienti/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista dei clienti associati all'utente autenticato
         * @description Ritorna i `clienti` per cui l'utente ha una riga in `user_clienti`.
         *
         *     Usato dal dashboard per popolare il dropdown "Seleziona cliente". Se
         *     l'utente non è associato a nessun cliente ritorna lista vuota (200,
         *     non 404) — il frontend mostra empty state con CTA "richiedi accesso".
         */
        get: operations["list_clienti_me_clienti_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clienti/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lettura profilo cliente */
        get: operations["get_cliente_clienti__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clienti/{cliente_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggiorna `needs` cliente e forza re-embed asincrono */
        post: operations["update_cliente_profile_clienti__cliente_id__profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top-k bandi consolidati per un cliente (cosine + rerank opzionale) */
        post: operations["post_match_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/{match_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verdetto consulente su un match (active learning) */
        post: operations["post_feedback_match__match_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cockpit/inbox-giornaliera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert giornalieri cross-cliente per l'operatore
         * @description Quattro sezioni cross-cliente per l'apertura giornata:
         *
         *     - `nuovi_top`: match rerank > 70% creati nelle ultime 24h, esclusi
         *       quelli già spostati dal consulente in `in_valutazione`/`scartato`.
         *     - `scadenze_imminenti`: bandi `in_valutazione` con scadenza <= 7gg.
         *     - `graduatorie_attese`: bandi in pipeline con
         *       `data_graduatoria_attesa_il <= today + 7gg`.
         *     - `eventi_recenti`: lifecycle event (proroga/FAQ/modulistica) ultime
         *       48h su bandi in pipeline.
         *
         *     Le quattro liste sono indipendenti: un bando può comparire in più
         *     di una sezione (nuovi_top + scadenza imminente è raro ma possibile).
         *     Filtro implicito sui `cliente_id` con access row in `user_clienti`.
         */
        get: operations["get_inbox_giornaliera_cockpit_inbox_giornaliera_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cockpit/workspace/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace cliente: kanban pre-candidatura + esiti attesi
         * @description Pipeline pre-candidatura del cliente, raggruppata per stato kanban,
         *     + lista bandi con `data_graduatoria_attesa_il` nei prossimi 30gg.
         *
         *     Il payload è già pre-grouped server-side: il frontend bind-a `nuovo`,
         *     `in_valutazione`, `scartato` direttamente alle 3 colonne kanban senza
         *     fare `groupBy` lato client.
         */
        get: operations["get_workspace_cockpit_workspace__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cockpit/bando/{cliente_id}/{bando_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dettaglio bando per il cockpit operatore (cliente-scoped)
         * @description Vista aggregata del bando per la pagina `/dashboard/bandi/[id]`.
         *
         *     Aggrega bando consolidato + pipeline (se esiste) + match Sonnet
         *     (score + motivazioni) + lifecycle events. Una sola fetch lato frontend
         *     per popolare l'intera pagina di dettaglio.
         *
         *     Auth: gating su `authorize_cliente_access` — l'utente deve avere una
         *     access row in `user_clienti` per il `cliente_id`. Il `bando_id` è
         *     libero (i bandi consolidati sono globali, non cliente-scoped) ma il
         *     payload include solo i dati pertinenti al cliente passato (pipeline +
         *     match della coppia).
         */
        get: operations["get_bando_detail_cockpit_bando__cliente_id___bando_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cockpit/pipeline/{cliente_id}/{bando_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert stato pipeline (kanban drag&drop o decisione triage)
         * @description Upsert idempotente sulla coppia (cliente, bando) con il nuovo stato.
         *
         *     Chiamata ogni volta che il consulente:
         *       - sposta una card kanban (drag&drop) → `stato='in_valutazione'` o
         *         `'scartato'`;
         *       - apre il drawer di un nuovo bando in inbox e clicca "valuta" o
         *         "scarta";
         *       - aggiorna note o motivo di scarto su una card già esistente.
         *
         *     `autore` è l'`user_id` del JWT (string UUID) — permette audit trail
         *     "ultima mossa: gianni 3 minuti fa" senza accoppiarsi a tabelle utenti
         *     esterne (lo user reale vive in `civika.it.users` via ADR-025).
         */
        post: operations["post_pipeline_stato_cockpit_pipeline__cliente_id___bando_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista alert ZERO MISS (shortfall + fonte_silente) */
        get: operations["list_alerts_coverage_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage-audit/segnalazioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Segnalazione manuale di bando mancante (ADR-011 Mecc. 4)
         * @description ADR-011 Mecc. 4: persiste una segnalazione consulente come audit.
         *
         *     Il record sarà visibile nella dashboard `/dashboard/coverage-alerts`
         *     con card dedicata (verde/teal). Non c'è validazione di unicità: la
         *     stessa segnalazione duplicata produce 2 record — la diagnostica umana
         *     deve poterne distinguere lo stato (es. due consulenti diversi).
         */
        post: operations["create_segnalazione_coverage_audit_segnalazioni_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BandiListItem
         * @description Riga del catalogo globale `GET /bandi` (super_admin).
         *
         *     Vista compatta del bando consolidato senza arricchimenti per-cliente
         *     (niente score, niente pipeline). Il super_admin la usa per esplorare
         *     il corpus, filtrare e poi aprire il dettaglio passando un cliente.
         */
        BandiListItem: {
            bando: components["schemas"]["BandoConsolidatoRead"];
            /**
             * N Clienti Match
             * @description Numero di clienti CIVIKA con almeno un `match_proposti` su questo bando. Indica popolarità/attivazione del bando nel parco clienti.
             * @default 0
             */
            n_clienti_match: number;
        };
        /**
         * BandiListPage
         * @description Risposta paginata `GET /bandi`.
         */
        BandiListPage: {
            /** Items */
            items: components["schemas"]["BandiListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * BandoClientePipelineRead
         * @description Riga `bando_cliente_pipeline` come letta dal DB.
         */
        BandoClientePipelineRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /**
             * Bando Consolidato Id
             * Format: uuid
             */
            bando_consolidato_id: string;
            stato_pipeline: components["schemas"]["BandoPipelineStato"];
            /** Note Consulente */
            note_consulente: string | null;
            /** Scartato Motivo */
            scartato_motivo: string | null;
            /** Autore */
            autore: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BandoClientePipelineUpsert
         * @description Body POST /pipeline/{cliente_id}/{bando_id} — sposta una coppia
         *     (cliente, bando) lungo il kanban pre-candidatura.
         *
         *     `note_consulente` è libero (sempre opzionale). `scartato_motivo` è
         *     convenzionalmente valorizzato solo quando `stato='scartato'` — non
         *     vincolato a livello DB perché l'UX preserva la possibilità di scartare
         *     senza motivo nei contesti di triage rapido.
         */
        BandoClientePipelineUpsert: {
            stato: components["schemas"]["BandoPipelineStato"];
            /** Note Consulente */
            note_consulente?: string | null;
            /** Scartato Motivo */
            scartato_motivo?: string | null;
        };
        /** BandoConsolidatoRead */
        BandoConsolidatoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Bando Estratto Canonico Id
             * Format: uuid
             */
            bando_estratto_canonico_id: string;
            /** Cluster Hash */
            cluster_hash: string;
            /** Titolo */
            titolo: string;
            /** Ente Emittente */
            ente_emittente: string;
            /** Scadenza */
            scadenza: string | null;
            /** Importo Totale Centesimi */
            importo_totale_centesimi: number | null;
            /** Territorio */
            territorio: {
                [key: string]: unknown;
            } | null;
            /** Beneficiari Tipo */
            beneficiari_tipo: {
                [key: string]: unknown;
            } | null;
            /** Categoria Beneficiari */
            categoria_beneficiari?: components["schemas"]["CategoriaBeneficiari"][] | null;
            /** Settori Ateco */
            settori_ateco: {
                [key: string]: unknown;
            } | null;
            stato: components["schemas"]["BandoStato"];
            livello: components["schemas"]["FonteLivello"] | null;
            /** Lingua Originale */
            lingua_originale: string | null;
            /** Page Url Canonico */
            page_url_canonico: string | null;
            /** Ultimo Check At */
            ultimo_check_at: string | null;
            /** Frequenza Check Ore */
            frequenza_check_ore: number;
            /** Data Graduatoria Attesa Il */
            data_graduatoria_attesa_il?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BandoDetailRead
         * @description Risposta GET /cockpit/bando/{cliente_id}/{bando_id} — pagina dettaglio.
         *
         *     Aggrega tutto ciò che il cockpit operatore mostra in `/dashboard/bandi/[id]`:
         *     bando consolidato canonico, riga pipeline (se esiste), score+motivazioni
         *     rerank, lifecycle events, documenti (PDF sorgente + allegati), campi
         *     ricchi dell'estratto canonico (descrizione, cofinanziamento, criteri).
         *     Vista read-only — le mutazioni passano da
         *     `POST /cockpit/pipeline/{cliente_id}/{bando_id}`.
         */
        BandoDetailRead: {
            cliente: components["schemas"]["ClienteRead"];
            bando: components["schemas"]["BandoConsolidatoRead"];
            /** @description Riga `bando_cliente_pipeline` per la coppia (cliente, bando). None se l'operatore non ha ancora interagito (mai mosso da inbox). */
            pipeline?: components["schemas"]["BandoClientePipelineRead"] | null;
            /** @description Score rerank Sonnet 4 dimensioni quando match_proposti esiste. */
            match_scores?: components["schemas"]["MatchScoresRead"] | null;
            /** @description Motivazioni testuali Sonnet, allineate a match_scores. */
            motivazioni?: components["schemas"]["MatchMotivazioniRead"] | null;
            /** Match Id */
            match_id?: string | null;
            /**
             * Eventi
             * @description Lifecycle events su questo bando, ordinati per `rilevato_at` discendente. Include proroghe, FAQ aggiunte, modulistica, graduatoria pubblicata.
             */
            eventi?: components["schemas"]["BandoEventoRead"][];
            /**
             * Documenti
             * @description PDF sorgente canonico (presigned R2, 1h) + allegati esterni dichiarati nella pagina fonte. Vuota se nessun raw_document ingerito e nessun allegato in `link_allegati`.
             */
            documenti?: components["schemas"]["DocumentoBandoRead"][];
            /** @description Campi ricchi dell'estratto canonico (descrizione, cofinanziamento, criteri, CUP/CIG). None se il consolidato non ha estratto canonico associato (non dovrebbe accadere, edge case storico). */
            bando_estratto?: components["schemas"]["BandoEstrattoRichRead"] | null;
        };
        /**
         * BandoEstrattoRichRead
         * @description Campi "ricchi" dell'estratto canonico esposti in scheda dettaglio.
         *
         *     `BandoConsolidatoRead` mostra solo i campi normalizzati per il listing.
         *     Per la pagina dettaglio servono anche descrizione lunga, criteri di
         *     cofinanziamento, modalità di presentazione, note libere, codici CUP/CIG
         *     — tutti residenti su `bandi_estratti`. Niente embedding o campi tecnici
         *     di pipeline.
         */
        BandoEstrattoRichRead: {
            /** Oggetto Descrizione */
            oggetto_descrizione?: string | null;
            /** Cofinanziamento Pct */
            cofinanziamento_pct?: string | null;
            /** Spese Ammissibili */
            spese_ammissibili?: {
                [key: string]: unknown;
            } | null;
            /** Modalita Presentazione */
            modalita_presentazione?: string | null;
            /** Note */
            note?: string | null;
            /** Codice Cup */
            codice_cup?: string | null;
            /** Codice Cig */
            codice_cig?: string | null;
            /** Importo Max Beneficiario Centesimi */
            importo_max_beneficiario_centesimi?: number | null;
            /** Data Pubblicazione */
            data_pubblicazione?: string | null;
        };
        /** BandoEventoRead */
        BandoEventoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Bando Consolidato Id
             * Format: uuid
             */
            bando_consolidato_id: string;
            tipo_evento: components["schemas"]["BandoEventoTipo"];
            /**
             * Rilevato At
             * Format: date-time
             */
            rilevato_at: string;
            severita: components["schemas"]["BandoEventoSeverita"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Page Content Hash Pre */
            page_content_hash_pre: string | null;
            /** Page Content Hash Post */
            page_content_hash_post: string | null;
            /** Consulente Notificato */
            consulente_notificato: boolean;
            /** Cliente Notificato */
            cliente_notificato: boolean;
            /** Raw Document Pre Id */
            raw_document_pre_id: string | null;
            /** Raw Document Post Id */
            raw_document_post_id: string | null;
        };
        /**
         * BandoEventoSeverita
         * @description Severità di un bando_evento per il routing notifiche.
         * @enum {string}
         */
        BandoEventoSeverita: "low" | "medium" | "high" | "critical";
        /**
         * BandoEventoTipo
         * @description Lifecycle event su un bando consolidato (ADR-017).
         * @enum {string}
         */
        BandoEventoTipo: "proroga_scadenza" | "faq_aggiunta" | "allegato_aggiornato" | "modulistica_pubblicata" | "chiarimento_minore" | "revoca_o_ritiro" | "graduatoria_pubblicata";
        /**
         * BandoPipelineStato
         * @description Stato pre-candidatura di una coppia (cliente, bando) — ADR-035.
         *
         *     Tracciamento della decisione del consulente *prima* che si decida di
         *     candidarsi. Quando si decide di candidarsi, NON si aggiunge un quarto
         *     stato: si crea un record in `candidature` con `stato='in_preparazione'`
         *     (delegando ad ADR-018 la fase post-decisione).
         *
         *     Allineato all'enum Postgres `bando_pipeline_stato` (migration 0009).
         * @enum {string}
         */
        BandoPipelineStato: "nuovo" | "in_valutazione" | "scartato";
        /**
         * BandoStato
         * @enum {string}
         */
        BandoStato: "aperto" | "in_proroga" | "chiuso" | "ritirato" | "in_attesa_aggiudicazione" | "missed_opportunity" | "graduatoria_pubblicata" | "draft_low_confidence";
        /**
         * CategoriaBeneficiari
         * @description Categorie normalizzate dei beneficiari ammissibili a un bando.
         *
         *     Popolato dal parser Haiku in fase di estrazione strutturata, oltre alla
         *     lista libera `beneficiari_tipo.valori`. Permette il filtro hard SQL su
         *     compatibilità cliente↔bando senza euristica su stringhe libere
         *     (vedi `civika_matcher.eligibility`).
         *
         *     Un bando può avere più categorie (es. PNRR rigenerazione urbana ammette
         *     `enti_locali` + `pmi` + `ets` insieme): il campo è ARRAY.
         *
         *     Allineato all'enum Postgres `categoria_beneficiari` (migration 0010).
         * @enum {string}
         */
        CategoriaBeneficiari: "enti_locali" | "regioni" | "province" | "pa_centrale" | "gal" | "pmi" | "grandi_imprese" | "persone_fisiche" | "professionisti" | "ets" | "cooperative_sociali" | "ricerca" | "operatori_tlc" | "operatori_energia" | "agricoltori" | "consorzi" | "altro";
        /** ClienteRead */
        ClienteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nome */
            nome: string;
            tipo_ente: components["schemas"]["ClienteTipoEnte"];
            /** Codice Istat */
            codice_istat: string | null;
            /** Partita Iva */
            partita_iva: string | null;
            /** Territorio */
            territorio: {
                [key: string]: unknown;
            } | null;
            /** Settori Attivita */
            settori_attivita: {
                [key: string]: unknown;
            } | null;
            /** Capacita Cofinanziamento Centesimi */
            capacita_cofinanziamento_centesimi: number | null;
            /** Needs */
            needs: string | null;
            /** Attivo */
            attivo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ClienteTipoEnte
         * @enum {string}
         */
        ClienteTipoEnte: "comune" | "unione_comuni" | "gal" | "provincia" | "pmi" | "grande_impresa" | "ets" | "cooperativa_sociale" | "altro";
        /**
         * ClienteUpdateNeeds
         * @description Endpoint dedicato `POST /clienti/{id}/profile` (vedi CLAUDE.md sez. 3).
         *
         *     `needs` deve essere non vuoto: serve almeno una frase libera che
         *     descriva cosa il cliente sta cercando. Stringhe blank vengono
         *     respinte con 422 prima ancora di toccare il DB.
         */
        ClienteUpdateNeeds: {
            /** Needs */
            needs: string;
        };
        /**
         * CoverageAuditAlertRead
         * @description Vista arricchita di `CoverageAuditRead` per la UI alert.
         *
         *     Include `fonte_nome` e `fonte_livello` via JOIN — evita N+1 lato
         *     client. Usato dall'endpoint `GET /coverage-alerts` per la dashboard
         *     operativa CIVIKA che mostra le fonti con shortfall/fonte_silente.
         *
         *     Per ADR-011 Mecc. 1 (cross-source dedup inverso) `bando_consolidato_id`
         *     è valorizzato e `bando_titolo` arriva dalla LEFT JOIN su
         *     `bandi_consolidati`. Per Mecc. 2 (shortfall di periodo) entrambi sono
         *     `None`. Per Mecc. 4 (`tipo_segnalazione = 'manual_report'`) anche
         *     `fonte_id` può essere `None`. Il discriminator dashboard usa, in
         *     ordine di precedenza: `tipo_segnalazione` → `bando_consolidato_id` →
         *     fallback Mecc. 2.
         */
        CoverageAuditAlertRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Fonte Id */
            fonte_id?: string | null;
            /** Fonte Nome */
            fonte_nome?: string | null;
            fonte_livello?: components["schemas"]["FonteLivello"] | null;
            /**
             * Periodo Inizio
             * Format: date
             */
            periodo_inizio: string;
            /**
             * Periodo Fine
             * Format: date
             */
            periodo_fine: string;
            /** Expected Count */
            expected_count: number;
            /** Actual Count */
            actual_count: number;
            /** Delta Pct */
            delta_pct: string;
            esito: components["schemas"]["CoverageAuditEsito"];
            /** Note */
            note: string | null;
            /** Bando Consolidato Id */
            bando_consolidato_id?: string | null;
            /** Bando Titolo */
            bando_titolo?: string | null;
            /** Tipo Segnalazione */
            tipo_segnalazione?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CoverageAuditEsito
         * @description Esito di una finestra di Coverage Audit (ADR-011, Strato 10).
         *
         *     Allineato all'enum Postgres `coverage_audit_esito` (migration 0002).
         * @enum {string}
         */
        CoverageAuditEsito: "ok" | "shortfall" | "overshoot" | "fonte_silente";
        /** CoverageAuditRead */
        CoverageAuditRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Fonte Id */
            fonte_id?: string | null;
            /**
             * Periodo Inizio
             * Format: date
             */
            periodo_inizio: string;
            /**
             * Periodo Fine
             * Format: date
             */
            periodo_fine: string;
            /** Expected Count */
            expected_count: number;
            /** Actual Count */
            actual_count: number;
            /** Delta Pct */
            delta_pct: string;
            esito: components["schemas"]["CoverageAuditEsito"];
            /** Note */
            note: string | null;
            /** Bando Consolidato Id */
            bando_consolidato_id?: string | null;
            /** Tipo Segnalazione */
            tipo_segnalazione?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CoverageAuditSegnalazioneCreate
         * @description Payload UI per segnalazione manuale di bando mancante (ADR-011 Mecc. 4).
         *
         *     Il consulente CIVIKA ha trovato altrove (Gazzetta, blog di settore,
         *     cliente) un bando rilevante che il sistema non ha intercettato. Apre
         *     un alert nella dashboard ZERO MISS che alimenta la diagnostica
         *     downstream (perché non l'abbiamo? quale fonte avrebbe dovuto darcelo?).
         *
         *     Tutti i campi tranne `titolo` sono opzionali: il consulente potrebbe
         *     avere solo un titolo + URL, oppure conoscere ente e scadenza ma non
         *     descrizione. La diagnostica avviene a valle, non al momento della
         *     segnalazione.
         */
        CoverageAuditSegnalazioneCreate: {
            /** Titolo */
            titolo: string;
            /** Url Fonte */
            url_fonte?: string | null;
            /** Ente Pubblicatore */
            ente_pubblicatore?: string | null;
            /** Scadenza Dichiarata */
            scadenza_dichiarata?: string | null;
            /** Descrizione */
            descrizione?: string | null;
        };
        /**
         * DocumentoBandoRead
         * @description Singolo documento associato al bando: sorgente canonica o allegato.
         *
         *     `kind` discrimina la natura del riferimento:
         *       - `sorgente`: il `raw_document` canonico ingerito da R2 — il PDF/HTML
         *         che il parser ha letto per estrarre i dati. `url` è un presigned URL
         *         R2 a 1h. Sempre presente quando esiste un canonical estratto con
         *         `r2_key`.
         *       - `allegato`: un allegato dichiarato nella pagina sorgente (link
         *         `link_allegati` JSONB, popolato dall'estrazione Haiku). `url` è
         *         l'URL pubblico originale della fonte — non passa da R2.
         *
         *     `mime_type`, `size_bytes` sono valorizzati solo per `sorgente` (li
         *     abbiamo da `raw_documents`); per gli allegati esterni li lasciamo None
         *     finché non li scaricheremo lato pipeline.
         */
        DocumentoBandoRead: {
            /** Kind */
            kind: string;
            /** Titolo */
            titolo: string;
            /** Url */
            url: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /**
         * FeedbackMatchCreate
         * @description Payload `POST /match/{match_id}/feedback` — verdetto consulente.
         *
         *     `autore` è valorizzato lato server con lo `user_id` del JWT — non viene
         *     accettato dal client. `commento` è opzionale ma fortemente raccomandato
         *     per i `non_pertinente`: senza spiegazione il segnale di learning è muto.
         */
        FeedbackMatchCreate: {
            valutazione: components["schemas"]["FeedbackValutazione"];
            /** Tag Motivo */
            tag_motivo?: {
                [key: string]: unknown;
            } | null;
            /** Commento */
            commento?: string | null;
        };
        /** FeedbackMatchRead */
        FeedbackMatchRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            valutazione: components["schemas"]["FeedbackValutazione"];
            /** Tag Motivo */
            tag_motivo: {
                [key: string]: unknown;
            } | null;
            /** Commento */
            commento: string | null;
            /** Autore */
            autore: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeedbackValutazione
         * @description Verdetto consulente su un `match_proposto` (migration 0001 enum
         *     `feedback_valutazione`). Active learning loop Strato 9.
         * @enum {string}
         */
        FeedbackValutazione: "pertinente" | "borderline" | "non_pertinente";
        /**
         * FonteLivello
         * @enum {string}
         */
        FonteLivello: "regionale" | "nazionale" | "europeo";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InboxBandoNuovo
         * @description Riga 'nuovo bando alto score' nella Inbox del giorno.
         */
        InboxBandoNuovo: {
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /** Cliente Nome */
            cliente_nome: string;
            bando: components["schemas"]["BandoConsolidatoRead"];
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Score Complessivo */
            score_complessivo: number;
            alert_level: components["schemas"]["MatchAlertLevel"];
        };
        /**
         * InboxEventoRecente
         * @description Riga 'lifecycle event recente su bando in pipeline' (ADR-017).
         */
        InboxEventoRecente: {
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /** Cliente Nome */
            cliente_nome: string;
            bando: components["schemas"]["BandoConsolidatoRead"];
            tipo_evento: components["schemas"]["BandoEventoTipo"];
            severita: components["schemas"]["BandoEventoSeverita"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * InboxGiornalieraRead
         * @description Risposta GET /inbox-giornaliera — alert aggregati di apertura giornata.
         *
         *     Quattro liste tematiche pronte per la sezione "Inbox del giorno" del
         *     cockpit. Filtrate sui clienti per cui l'utente ha access row in
         *     `user_clienti`. Ordinate per priorità decrescente (alert_level/giorni
         *     residui/data ascendente, dipende dalla sezione).
         */
        InboxGiornalieraRead: {
            /** Nuovi Top */
            nuovi_top: components["schemas"]["InboxBandoNuovo"][];
            /** Scadenze Imminenti */
            scadenze_imminenti: components["schemas"]["InboxScadenzaImminente"][];
            /** Graduatorie Attese */
            graduatorie_attese: components["schemas"]["InboxGraduatoriaAttesa"][];
            /** Eventi Recenti */
            eventi_recenti: components["schemas"]["InboxEventoRecente"][];
        };
        /**
         * InboxGraduatoriaAttesa
         * @description Riga 'graduatoria attesa entro 7 giorni' nella Inbox.
         */
        InboxGraduatoriaAttesa: {
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /** Cliente Nome */
            cliente_nome: string;
            bando: components["schemas"]["BandoConsolidatoRead"];
            /**
             * Data Graduatoria Attesa Il
             * Format: date
             */
            data_graduatoria_attesa_il: string;
        };
        /**
         * InboxScadenzaImminente
         * @description Riga 'scadenza ≤ 7 giorni su bando in valutazione' nella Inbox.
         */
        InboxScadenzaImminente: {
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /** Cliente Nome */
            cliente_nome: string;
            bando: components["schemas"]["BandoConsolidatoRead"];
            /** Giorni Residui */
            giorni_residui: number;
        };
        /**
         * MatchAlertLevel
         * @description Severità di un match proposto (Strato 9, migration 0001 enum `match_alert_level`).
         *
         *     Derivata dallo `score_complessivo` del rerank Sonnet. Usata per ordinare
         *     e colorare le card dashboard senza ricalcolare la soglia client-side.
         * @enum {string}
         */
        MatchAlertLevel: "low" | "medium" | "high" | "critical";
        /**
         * MatchMotivazioniRead
         * @description Motivazione testuale (~140 char) per ciascuna dimensione del rerank.
         *
         *     Esposta accanto a `MatchScoresRead` quando `rerank=true` — alimenta la
         *     modale "Perché questo score?" del cockpit operatore (ADR-035), che
         *     aiuta i consulenti junior a leggere ogni peso in modo separato.
         */
        MatchMotivazioniRead: {
            /** Pertinenza */
            pertinenza: string;
            /** Fattibilita */
            fattibilita: string;
            /** Urgenza */
            urgenza: string;
            /** Valore Atteso */
            valore_atteso: string;
        };
        /**
         * MatchProposalRead
         * @description Singola proposta di match restituita da /match.
         *
         *     `score` ∈ [0, 1]: similarità coseno (1 - cosine_distance). Più alto è
         *     meglio. Non è una probabilità — è un proxy di vicinanza semantica.
         *
         *     `rerank` e `motivazioni` sono valorizzati solo se la richiesta aveva
         *     `rerank=true`: in quel caso il modello Sonnet ha prodotto score
         *     multi-dimensionali e una motivazione testuale per ciascuna dimensione.
         */
        MatchProposalRead: {
            bando: components["schemas"]["BandoConsolidatoRead"];
            /** Score */
            score: number;
            rerank?: components["schemas"]["MatchScoresRead"] | null;
            motivazioni?: components["schemas"]["MatchMotivazioniRead"] | null;
            /**
             * Match Id
             * @description ID del `match_proposto` persistito quando il rerank è stato richiesto. None se la chiamata ha usato solo cosine baseline. Necessario per l'endpoint feedback POST /match/{match_id}/feedback.
             */
            match_id?: string | null;
        };
        /**
         * MatchRequest
         * @description Body POST /match — richiesta di match semantico per un cliente.
         *
         *     `top_k` è limitato a 50 per evitare scansioni costose lato DB e
         *     response giganti — il consulente difficilmente legge oltre 20 match.
         *     `livello` permette di filtrare hard reg/naz/EU lato SQL prima del rerank.
         *     `rerank=True` attiva il rerank Sonnet 4.6 multi-dimensionale (A4.3) sui
         *     top-k cosine: produce pertinenza/fattibilità/urgenza/valore_atteso +
         *     quattro motivazioni per ogni candidato (una per dimensione, alimenta
         *     la modale "Perché questo score?" del cockpit operatore — ADR-035).
         *     Costo aggiuntivo ~0.01-0.03€ a chiamata.
         */
        MatchRequest: {
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            livello?: components["schemas"]["FonteLivello"] | null;
            /**
             * Rerank
             * @default false
             */
            rerank: boolean;
        };
        /**
         * MatchScoresRead
         * @description Score multi-dimensionali prodotti dal rerank Sonnet (A4.3).
         *
         *     Tutti i campi sono float ∈ [0, 1]. `score_complessivo` è la media
         *     pesata interna scelta dal modello — è il valore principale per
         *     ordinare i risultati ranked.
         */
        MatchScoresRead: {
            /** Pertinenza */
            pertinenza: number;
            /** Fattibilita */
            fattibilita: number;
            /** Urgenza */
            urgenza: number;
            /** Valore Atteso */
            valore_atteso: number;
            /** Score Complessivo */
            score_complessivo: number;
        };
        /**
         * PipelineKanbanItem
         * @description Item del kanban workspace cliente: bando + stato pipeline + score.
         *
         *     `match_score_complessivo` è valorizzato quando esiste un record in
         *     `match_proposti` per la coppia (cliente, bando) — il consulente vede
         *     il peso che il motore ha dato al match accanto al suo verdetto manuale.
         */
        PipelineKanbanItem: {
            bando: components["schemas"]["BandoConsolidatoRead"];
            stato_pipeline: components["schemas"]["BandoPipelineStato"];
            /** Note Consulente */
            note_consulente: string | null;
            /** Scartato Motivo */
            scartato_motivo: string | null;
            /**
             * Match Score Complessivo
             * @description Score complessivo (0-100) dal rerank Sonnet quando disponibile, altrimenti None. Permette al kanban di ordinare per priorità.
             */
            match_score_complessivo?: number | null;
            match_alert_level?: components["schemas"]["MatchAlertLevel"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkspaceClienteRead
         * @description Risposta GET /workspace/{cliente_id} — dati per il workspace operatore.
         *
         *     Il payload è già pre-raggruppato server-side: il frontend non deve fare
         *     `groupBy(stato)` o cercare quali bandi hanno una graduatoria attesa, le
         *     tre liste sono pronte per essere bindate ai componenti kanban.
         */
        WorkspaceClienteRead: {
            cliente: components["schemas"]["ClienteRead"];
            /** Nuovo */
            nuovo: components["schemas"]["PipelineKanbanItem"][];
            /** In Valutazione */
            in_valutazione: components["schemas"]["PipelineKanbanItem"][];
            /** Scartato */
            scartato: components["schemas"]["PipelineKanbanItem"][];
            /**
             * Esiti Attesi
             * @description Bandi con `data_graduatoria_attesa_il <= today + 30gg`, ordinati per data ascendente. Alimenta la colonna 'Esiti attesi' del kanban e l'highlight della Inbox.
             */
            esiti_attesi?: components["schemas"]["BandoConsolidatoRead"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_bandi_bandi_get: {
        parameters: {
            query?: {
                q?: string | null;
                stato?: components["schemas"]["BandoStato"] | null;
                livello?: components["schemas"]["FonteLivello"] | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandiListPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clienti_me_clienti_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cliente_clienti__cliente_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cliente_profile_clienti__cliente_id__profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteUpdateNeeds"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_match_match_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchProposalRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_feedback_match__match_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackMatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inbox_giornaliera_cockpit_inbox_giornaliera_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxGiornalieraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_cockpit_workspace__cliente_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceClienteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bando_detail_cockpit_bando__cliente_id___bando_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
                bando_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandoDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_pipeline_stato_cockpit_pipeline__cliente_id___bando_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
                bando_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BandoClientePipelineUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandoClientePipelineRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_coverage_alerts_get: {
        parameters: {
            query?: {
                /** @description Solo audit con periodo_fine >= since (ISO date). Default: oggi - 30 giorni. */
                since?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageAuditAlertRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_segnalazione_coverage_audit_segnalazioni_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverageAuditSegnalazioneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageAuditRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
